services:
  ui:
    container_name: online-sushi-bar-api
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
    - 7274:7274 
  
  seq:
    image: datalust/seq:latest
    container_name: online-sushi-bar-api.seq
    environment:
    - ACCEPT_EULA=Y
    ports:
    - 5341:5341
    - 8081:80
  
  database:
    image: postgres:latest
    container_name: online-sushi-bar-api.database
    environment:
    - POSTGRES_DB=OnlineSushiBarDb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=1234
    ports:
    - 5432:5432
    volumes:
    - "online-sushi-bar-volume:/app"  
    
  redis:
    image: redis:latest
    container_name: online-sushi-bar-api.redis
    restart: always
    ports:
    - 6379:6379 

volumes:
  online-sushi-bar-volume:
    external: true