services:
  ui:
    container_name: online-sushi-bar-api
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
    - 7274:7274 
  
  seq:
    image: datalust/seq:latest
    container_name: online-sushi-bar-api.seq
    environment:
    - ACCEPT_EULA=Y
    ports:
    - 5341:5341
    - 8081:80
