name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: online-sushi-bar-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish" 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./online-sushi-bar-api.sln

      - name: build
        run: dotnet build ./online-sushi-bar-api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./online-sushi-bar-api.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployment
        uses: azure/web-apps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
